### PR TITLE
creating ui design for splashscreen/login/register pages

### PR DESCRIPTION
**Pull request by mohamed-jedata**
Hi @hamzariffic  , @rileyhawk1417 
Check the ui pages I made
I put them in ui folder

### CODE REVIEW

**Comment by fred-juma** [comment]
@rileyhawk1417 @hamzariffic I see this PR done by @mohamed-jedata. To avoid duplication and clutter, once you review and approve his PR, you can update the readme *src* with this new path and then delete the previous *screenshots* directory that I created.

**Comment by rileyhawk1417** [comment]
Noted will do that

**Comment by rileyhawk1417** [comment]
@mohamed-jedata we can just remove the pdf since it just has the images that are already in a folder.

**Comment by mohamed-jedata** [comment]
@rileyhawk1417 All right, as for the splash screen , we can create it once the logo is done

**Pull request merged**
